import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SiteTheme from "@/components/wrappers/SiteTheme";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-gradient-to-b from-indigo-900 via-indigo-800 to-indigo-700`}
      >
        <SiteTheme>
          <Header />
          <div className="min-h-screen w-full flex flex-col">
            <main className="flex-1 w-full px-0 py-0">
              {children}
            </main>
          </div>
          <Footer />
        </SiteTheme>
      </body>
    </html>
  );
}
